const HEADER_SIZE = 4;
const SIGNATURE_SIZE = 32;
const MAX_PAYLOAD = 1024;

const MIN_AUTH_PACKET = HEADER_SIZE + SIGNATURE_SIZE;
const MAX_PACKET = HEADER_SIZE + SIGNATURE_SIZE + MAX_PAYLOAD;

const ACTIVE_CONN = 0;
const PASSIVE_CONN = 1;

const CONNECTION_FLAGS = {
  CONNECTED:       (1 << 0),
  PING_LOCKED:     (1 << 1),
  EXPECTING_PEERS: (1 << 2),
  EXPECTING_CONN:  (1 << 3),
};

const NETWORK_MAGIC = 0xbe48e224b3ae4681n;
const PROTOCOl_VERSION = 0;

const MAX_ACTIVE_INTERNAL = 2;
const MAX_ACTIVE_EXTERNAL = 1;
const MAX_ACTIVE = MAX_ACTIVE_INTERNAL + MAX_ACTIVE_EXTERNAL;

module.exports = {
  HEADER_SIZE,
  SIGNATURE_SIZE,
  MIN_AUTH_PACKET,
  MAX_PACKET,
  ACTIVE_CONN,
  PASSIVE_CONN,
  CONNECTION_FLAGS,
  NETWORK_MAGIC,
  PROTOCOl_VERSION,
  MAX_ACTIVE_INTERNAL,
  MAX_ACTIVE_EXTERNAL,
  MAX_ACTIVE
};